server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://goalajuma-database.c9gksc4siyzc.ap-northeast-2.rds.amazonaws.com:3306/goalajuma
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false