spring:
  config:
    activate:
      on-profile: dev-token

security:
  jwt:
    token:
      secretKey: eeosoverflowsecretekeyeeosoverflowsecretekey
      access:
        validTime: 2629800000
      refresh:
        validTime: 5259600000
